In [1]:
import numpy as np

In [2]:
x=np.array([[0,1,0],[1,1,0],[1,0,1],[0,0,1]])
y=np.array([[0],[1],[1],[0]])
print(x,"\n \n",y)

[[0 1 0]
 [1 1 0]
 [1 0 1]
 [0 0 1]] 
 
 [[0]
 [1]
 [1]
 [0]]


In [3]:
weights=np.random.random((3,1))
weights

array([[0.25903649],
       [0.16407814],
       [0.94526816]])

In [4]:
#sum(x*w)+bias
sum=np.dot(x,weights)+0.02
sum

array([[0.18407814],
       [0.44311463],
       [1.22430464],
       [0.96526816]])

In [5]:
#activation func
def act(x):
    return 1/(1+np.exp(-x))

In [6]:
pred=act(sum)

In [7]:
pred

array([[0.54589003],
       [0.60900093],
       [0.7728202 ],
       [0.72417534]])

In [8]:
pred.round()

array([[1.],
       [1.],
       [1.],
       [1.]])

In [9]:
error=y-pred
error

array([[-0.54589003],
       [ 0.39099907],
       [ 0.2271798 ],
       [-0.72417534]])

In [10]:
def gradient(x,error):
    return error*(x*(1-x))

In [11]:
w_change=gradient(pred,error)#gradient descent
weights=weights+np.dot(x.T,w_change)#back propogation(.T= transpose)

In [23]:
for i in range(0,1000):
    sum=np.dot(x,weights)+0.02
    pred=act(sum)
    mini=error
    error=y-pred
    w_change=gradient(pred,error)#gradient descent
    weights=weights+np.dot(x.T,w_change)#back propogation(.T= transpose)
    if mini.all()==error.all() & i>1:
        break
error

array([[-0.02335767],
       [ 0.01643278],
       [ 0.01643278],
       [-0.02335767]])

In [24]:
pred

array([[0.02335767],
       [0.98356722],
       [0.98356722],
       [0.02335767]])

In [25]:
pred.round()

array([[0.],
       [1.],
       [1.],
       [0.]])