In [1]:
import pandas as pd
df=pd.read_csv("Iris.csv")

In [2]:
x=df[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]

In [3]:
x.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [4]:
y=df["Species"]
y.head()


0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le=LabelEncoder()
y=le.fit_transform(y)

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
 x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=5) #maintain sequence n divides randomly 

In [10]:
x_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
39             5.1           3.4            1.5           0.2
53             5.5           2.3            4.0           1.3
79             5.7           2.6            3.5           1.0
10             5.4           3.7            1.5           0.2
50             7.0           3.2            4.7           1.4
..             ...           ...            ...           ...
8              4.4           2.9            1.4           0.2
73             6.1           2.8            4.7           1.2
144            6.7           3.3            5.7           2.5
118            7.7           2.6            6.9           2.3
99             5.7           2.8            4.1           1.3

[120 rows x 4 columns]

In [11]:
y_train

array([0, 1, 1, 0, 1, 0, 0, 2, 0, 2, 2, 1, 0, 0, 1, 2, 1, 2, 2, 0, 2, 0,
       0, 0, 0, 1, 1, 1, 1, 2, 1, 2, 2, 1, 0, 1, 0, 1, 2, 1, 2, 1, 2, 1,
       1, 1, 2, 1, 0, 2, 0, 0, 1, 0, 0, 2, 1, 0, 2, 0, 2, 1, 0, 0, 2, 1,
       1, 0, 0, 2, 1, 1, 0, 1, 2, 1, 0, 1, 2, 2, 2, 2, 0, 0, 1, 2, 0, 1,
       0, 0, 2, 1, 2, 0, 2, 0, 2, 0, 1, 0, 2, 2, 0, 2, 2, 2, 1, 0, 1, 0,
       0, 1, 2, 0, 2, 0, 1, 2, 2, 1])

In [12]:
x_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
82             5.8           2.7            3.9           1.2
134            6.1           2.6            5.6           1.4
114            5.8           2.8            5.1           2.4
42             4.4           3.2            1.3           0.2
109            7.2           3.6            6.1           2.5
57             4.9           2.4            3.3           1.0
1              4.9           3.0            1.4           0.2
70             5.9           3.2            4.8           1.8
25             5.0           3.0            1.6           0.2
84             5.4           3.0            4.5           1.5
66             5.6           3.0            4.5           1.5
133            6.3           2.8            5.1           1.5
102            7.1           3.0            5.9           2.1
107            7.3           2.9            6.3           1.8
26             5.0           3.4            1.6           0.4
23             5.1           3.3            1.7           0.5
123            6.3           2.7            4.9           1.8
130            7.4           2.8            6.1           1.9
21             5.1           3.7            1.5           0.4
12             4.8           3.0            1.4           0.1
71             6.1           2.8            4.0           1.3
128            6.4           2.8            5.6           2.1
48             5.3           3.7            1.5           0.2
72             6.3           2.5            4.9           1.5
88             5.6           3.0            4.1           1.3
148            6.2           3.4            5.4           2.3
74             6.4           2.9            4.3           1.3
96             5.7           2.9            4.2           1.3
63             6.1           2.9            4.7           1.4
132            6.4           2.8            5.6           2.2

In [13]:
from sklearn.naive_bayes import GaussianNB

In [14]:
model=GaussianNB()

In [15]:
model.fit(x_train,y_train)

GaussianNB()

In [16]:
y_pred=model.predict(x_test)

In [17]:
y_pred

array([1, 1, 2, 0, 2, 1, 0, 2, 0, 1, 1, 1, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2,
       0, 1, 1, 2, 1, 1, 1, 2])

In [18]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[ 8,  0,  0],
       [ 0, 10,  1],
       [ 0,  2,  9]])

In [19]:
from sklearn.metrics import accuracy_score
am=accuracy_score(y_test,y_pred)*100
am

90.0

In [20]:
for i in y_test,y_pred :
    print(i)

[1 2 2 0 2 1 0 1 0 1 1 2 2 2 0 0 2 2 0 0 1 2 0 1 1 2 1 1 1 2]
[1 1 2 0 2 1 0 2 0 1 1 1 2 2 0 0 2 2 0 0 1 2 0 1 1 2 1 1 1 2]


In [23]:
import numpy as np
new_y=np.array([[2.3,5.7,6.8,4.6]])
new_y

array([[2.3, 5.7, 6.8, 4.6]])

In [24]:
res=model.predict(new_y)

In [25]:
res

array([2])