In [1]:
import numpy as np

In [2]:
l1=[203,342,145,134]
n1=np.array([l1,l1])
n1

array([[203, 342, 145, 134],
       [203, 342, 145, 134]])

In [3]:
l1=[203,342,145,134]
#numpy array only accepts numeric values in lists
l2=np.array(l1)
print(l2)
print(l1)

[203 342 145 134]
[203, 342, 145, 134]


In [4]:
n3=np.zeros((3,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
n4=np.ones((5,3))
n4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
n5=np.arange(1,10).reshape(3,3)
n5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
n6=np.arange(1,100,2)
#(range_start,range_end,step count)

n6

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [8]:
n7=np.full([3,3],10)
n7

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [9]:
n8=np.random.randint(50,100,30)
#(range_start,range_end,no of values)
n8

array([76, 53, 62, 88, 60, 76, 87, 80, 68, 98, 66, 53, 65, 93, 74, 85, 93,
       65, 58, 79, 87, 72, 57, 95, 96, 93, 99, 68, 93, 90])

In [10]:
n9=np.sum(n5)
n9


45

In [11]:
n9=np.mean(n5)
n9


5.0

In [12]:
n9=np.median(n5)
n9


5.0

In [13]:
n9=np.std(n8)
n9
#standard deviation

14.402507497731852

In [14]:
n10=n3-n5
n10

array([[-1., -2., -3.],
       [-4., -5., -6.],
       [-7., -8., -9.]])

In [15]:
n11=n3+4
n11

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [16]:
n4-=9
n4

array([[-8., -8., -8.],
       [-8., -8., -8.],
       [-8., -8., -8.],
       [-8., -8., -8.],
       [-8., -8., -8.]])

In [35]:
a1=np.array([10,20,30,40])
a2=np.array([1,2,3,4])
m1=np.vstack([a1,a2])
m1

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [36]:
m2=np.hstack([a1,a2])
m2

array([10, 20, 30, 40,  1,  2,  3,  4])

In [37]:
m3=np.column_stack([a1,a2])
m3


array([[10,  1],
       [20,  2],
       [30,  3],
       [40,  4]])

In [38]:
m4=a1+a2
m4

array([11, 22, 33, 44])

In [39]:
a2.shape=(4,1)
a2

array([[1],
       [2],
       [3],
       [4]])

In [50]:
a1.shape=a2.shape=(2,2)
print(a1)
print(a2)
s1=np.sum([a1,a2],axis=1)
s1

[[10 20]
 [30 40]]
[[1 2]
 [3 4]]


array([[40, 60],
       [ 4,  6]])

In [53]:
a1[0:1] #splicing use 'Range operator ' i.e :

array([[10, 20]])

In [55]:
a1[1,0:2]

array([30, 40])

In [58]:
a2[0,1]

2

In [60]:
a1[-1:]

array([[30, 40]])

In [62]:
np.save("my array",a1)

In [66]:
n7=np.load("my array.npy")
n7

array([[10, 20],
       [30, 40]])